.MODEL SMALL            ;MODELO DE MEMORIA SERIA PEQUENO 

.STACK                  ;SEGMENTO DE PILA DETERMINADO 64

.DATA                   ;SEGMENTO DE DATOS

                        ;VARIABLE DE ATRIBUTO DE COLOR
                        
    ATRIB  DB  05       ;INICIALIZAR CON VALOR DEL COLOR 05 [MAGENTA]

.CODE                   ;SEGMENTO DE CODIGO

    MAIN PROC           ;INICIO DEL PROCESO DEL CODIGO [MAIN]
        
    MOV AX, @DATA       ;COMPARTIR VARIABLE DE DATA
    MOV DS, AX          ;GUARDA VARIABLE EN SEGMENTOS DE DATOS (DS)
                        
                        ;INICIALIZAMOS EN LA POSICION DEL RENGLON 1
                        
    MOV CX, 01          ;CX = POSICION DE COLUMNA (X)
    
    MOV AH, 00          ;SERVICIO DE ACTIVA MODO DE VIDEO
    MOV AL, 13H         ;AL = MODO DE VIDEO GRAFICO RESOLUCION [320x200]
    INT 10H             ;SERVICIO DE INTERRUPCION DEL CONTROL DE PANTALLA
     
    OTRO:               ;ETIQUETA PARA ESCRIBIR UN PIXEL 
    
        MOV DX, CX      ;DX = POSICION DE RENGLON (Y)
        MOV AL, ATRIB   ;AL = SERVICIO DE COLOR DEL PIXEL
        MOV AH, 0CH     ;SERVICIO DE ESCRIBIR PIXEL GRAFICO
        INT 10H         ;SERVICIO DE INTERRUPCION DEL CONTROL DE PANTALLA
        
        CMP CX, 101     ;COMPARAMOS CX CON 101
        JZ FIN          ;SALTAR CUANDO CX == 101 O CX-101=0
        
        INC CX          ;INCREMENTAR CX
                        
                        ;INCREMENTAR EL VALOR DEL COLOR
        ADD ATRIB, 02   ;SUMAR 2 AL ATRIBUTO DEL COLOR
        JMP OTRO        ;SALTAR A LA ETIQUETA OTRO
        
    FIN:                ;ETIQUETA PARA FINALIZAR CODIGO
    
        MOV AX, 4C00H   ;SERVICIO PARA TERMINA EL PROGRAMA
        INT 21H         ;SERVICIO DE INTERRUPCION DEL CONTROL DEL SISTEMA OPERATIVO
        
.EXIT                   ;SEGMENTO DE FIN DEL PROGRAMA

    MAIN ENDP           ;FIN DEL PROCESO DEL CODIGO
END                     ;DAR CIERRE AL ARCHIVO