
; Hola mundo

org 100h

MOV AH, 09H          ; SERVICIO PARA MANDA A IMPRIMIR UNA CADENA AH:09 HEXA
MOV DX, OFFSET MENSAJE  ; CARGA LA DIR EFECTIVA DE UN MENSAJE
INT 21H ; LLAMA A LA INT(eruccion) 21H DEL S.O.
INT 20H ; FIN DEL PROGRAMA RETORNA EL CONTROL AL S.O

MENSAJE DB "HOLA MUNDO :) !! $" ; DEFINE UNA CADENA COMO UNA SECUENCIA DE CARECTERES
; DEBE TERMINAR CON EL SIGNO DE $
;DB = DEFINE BYTE  DW = DIFINE 2 BYTE

ret




